language: scala

scala:
  -2.12.4

dist: trusty

sudo: false

#addons:
#  apt:
#    packages:
#      - libtesseract-dev
#      - libleptonica-dev
#      - tesseract-ocr-eng
#      - libpoppler-cpp-dev
#      - libmagick++-dev


before_install:
  - if [[ $TRAVIS_OS_NAME == linux   ]]; then LINUX=true; fi
  - if [[ $TRAVIS_OS_NAME == osx     ]]; then OSX=true; fi

install:
  #- if [[ $LINUX && "$CXX" = "g++" ]]; then export CXX="g++-6" CC="gcc-6"; fi
  - if test ! -d leptonica-$LEPT_VER/src; then curl -Ls https://github.com/DanBloomberg/leptonica/archive/$LEPT_VER.tar.gz | tar -xz; fi
  - if test ! -d leptonica-$LEPT_VER/usr; then cmake -Hleptonica-$LEPT_VER -Bleptonica-$LEPT_VER/build -DCMAKE_INSTALL_PREFIX=leptonica-$LEPT_VER/usr; fi
  - if test ! -e leptonica-$LEPT_VER/usr/lib/libleptonica.so; then make -C leptonica-$LEPT_VER/build install; fi

#before_install:
#  - sudo apt-get update -qq
#  - sudo apt-get install -y tesseract-ocr tesseract-ocr-eng tesseract-ocr-por

script:
  - sbt clean "++ 2.12.4 testOnly *ExtractorSuite *FileHandlerSuite *ImageProcessingSuite *OpenNLPSuite *FileHandlerGenSuite *GeneratorSuite *HTMLHandlerSuite *ConverterSuite"

## TODO correct java fatal error, maybe due to tesseract version ?