language: scala

scala:
  -2.12.4

sudo: required

dist: trusty

#addons:
#  apt:
#    packages:
#      - libtesseract-dev
#      - libleptonica-dev
#      - tesseract-ocr-eng
#      - libpoppler-cpp-dev
#      - libmagick++-dev

before_install:
  - sudo add-apt-repository ppa:alex-p/tesseract-ocr -y
  - sudo apt-get update -qq
  - sudo apt-get install -y tesseract-ocr tesseract-ocr-eng tesseract-ocr-por libtesseract-dev

script:
  - sbt clean "++ 2.12.4 testOnly *ExtractorSuite *FileHandlerSuite *ImageProcessingSuite *OpenNLPSuite *FileHandlerGenSuite *GeneratorSuite *HTMLHandlerSuite *ConverterSuite"

## TODO correct java fatal error, maybe due to tesseract version ?