language: scala

scala:
  -2.12.4

addons:
  apt:
    packages:
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - libpoppler-cpp-dev
      - libmagick++-dev

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y tesseract-ocr

script:
  - sbt clean "++ 2.12.4 testOnly *ExtractorSuite *FileHandlerSuite *ImageProcessingSuite *OpenNLPSuite *FileHandlerGenSuite *GeneratorSuite *HTMLHandlerSuite *ConverterSuite"
