language: scala

scala:
  -2.12.4

before_install:
#  - cd /home/usr
#  - mkdir tessdata
#  - wget -P /home/usr/tessdata https://github.com/tesseract-ocr/tessdata/blob/3.04.00/eng.traineddata?raw=true
#  - wget -P /home/usr/tessdata https://github.com/tesseract-ocr/tessdata/blob/3.04.00/por.traineddata?raw=true
#  - cd tessdata
#  - export TESSDATA_PREFIX = pwd
#  - cd ..
#  - sudo add-apt-repository ppa:alex-p/tesseract-ocr -y
#  - sudo apt-get update -qq
#  - sudo apt-get install -y tesseract-ocr tesseract-ocr-eng tesseract-ocr-por libtesseract-dev

script:
  - sbt clean "++ 2.12.4 testOnly *ExtractorSuite *FileHandlerSuite *ImageProcessingSuite *OpenNLPSuite *FileHandlerGenSuite *GeneratorSuite *HTMLHandlerSuite *ConverterSuite"

## TODO correct java fatal error, maybe due to tesseract version ?